import React, { useEffect, useState } from "react";
import axios from "axios";
import { useSelector } from "react-redux";
import { RootState } from "../../../redux/store";
import { toast } from "react-toastify";
import { apiRequest } from "../../../utils/api";
import { PropagateLoader } from "react-spinners";
import { InputTextarea } from "primereact/inputtextarea";
import usePayrollPeriods from "../../../hooks/hr/usePayRollPeriods";

interface ApprovalLevel {
  id: string;
  name: string;
}

interface Employee {
  first_name: string;
  last_name: string;
}

interface Net {
  id: string;
  employee_id: string;
  gross_pay: string;
  total_deductions: string;
  net_pay: string;
  status: string;
  approval_level: ApprovalLevel;
  employee: Employee;
}

interface PayrollRun {
  id: string;
  name: string;
  run_date: string;
  remarks: string;
  status: string;
  generated_by: {
    first_name: string;
    last_name: string;
    email: string;
  };
  nets: Net[];
}

interface ViewCalculatedNetModalProps {
  runId: string;
  onClose: () => void;
}

const ViewCalculatedNetModal: React.FC<ViewCalculatedNetModalProps> = ({
  runId,
  onClose,
}) => {
  const [run, setRun] = useState<PayrollRun | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedNetIds, setSelectedNetIds] = useState<string[]>([]);
  const [remarks, setRemarks] = useState("");
  const {refresh} = usePayrollPeriods()

  const token = useSelector((state: RootState) => state.userAuth.token);

  // ✅ Fetch run details
  const viewNetDetails = async () => {
    try {
      const response = await apiRequest(
        `/hr/payroll/runs/${runId}`,
        "GET",
        token.access_token
      );
      setRun(response.data);
    } catch (error: any) {
      toast.error(error?.response?.data?.message || "Failed to fetch details");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (runId) viewNetDetails();
  }, [runId]);

  // ✅ Toggle selection
  const handleSelect = (netId: string) => {
    setSelectedNetIds((prev) =>
      prev.includes(netId) ? prev.filter((id) => id !== netId) : [...prev, netId]
    );
  };

  // ✅ Approve selected
  const handleApprove = async () => {
    if (!run) return;
    if (selectedNetIds.length === 0) {
      toast.warning("Please select at least one employee to approve");
      return;
    }

    try {
      const payload = {
        nets: selectedNetIds.map((id) => ({ id, action: "approved" })),
        remarks,
      };

      await apiRequest('/payroll-runs/approve', "POST", token.access_token, payload);
      toast.success("Selected net pay(s) approved!");
      refresh();
      onClose();
    } catch (err: any) {
      toast.error(err?.response?.data?.message || "Failed to approve net pay");
    }
  };

  const handleReverse = async () => {
    if (!run) return;
    try {
      await axios.post(
        `/api/payroll-runs/${runId}/reverse`,
        {},
        { headers: { Authorization: `Bearer ${token.access_token}` } }
      );
      toast.success("Net pay reversed!");
    } catch (err: any) {
      toast.error(err?.response?.data?.message || "Failed to reverse net pay");
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40">
      <div className="bg-white w-11/12 max-w-5xl rounded-lg shadow-lg overflow-y-auto max-h-[90vh]">
        {/* Header */}
        <div className="flex justify-between items-center border-b px-6 py-4">
          <h2 className="text-xl font-bold">Net Pay Calculation</h2>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 text-2xl leading-none"
          >
            &times;
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          {loading && (
            <div className="flex justify-center">
              <PropagateLoader color="#007f80" />
            </div>
          )}

          {!loading && !run && (
            <p className="text-red-500">No data found.</p>
          )}

          {run && (
            <>
              <div className="border rounded-lg p-4 bg-gray-50">
                <h1 className="text-2xl font-bold mb-2">{run.name}</h1>
                <p><strong>Run Date:</strong> {run.run_date}</p>
                <p><strong>Remarks:</strong> {run.remarks}</p>
                <p>
                  <strong>Status:</strong>{" "}
                  <span className="font-medium text-teal-600">{run.status}</span>
                </p>
                <p>
                  <strong>Generated By:</strong>{" "}
                  {run.generated_by.first_name} {run.generated_by.last_name} (
                  {run.generated_by.email})
                </p>
              </div>

              {/* Nets Table */}
              <div>
                <h2 className="text-xl font-semibold mb-3">Net Pay Details</h2>
                <table className="w-full border-collapse border border-gray-200 text-sm">
                  <thead className="bg-gray-100">
                    <tr>
                      {run.status !== "approved" && (
                        <th className="border p-2">Select</th>
                      )}
                      <th className="border p-2">Employee</th>
                      <th className="border p-2">Gross Pay</th>
                      <th className="border p-2">Total Deductions</th>
                      <th className="border p-2">Net Pay</th>
                      <th className="border p-2">Status</th>
                      <th className="border p-2">Approval Level</th>
                    </tr>
                  </thead>
                  <tbody>
                    {run.nets.map((n) => (
                      <tr key={n.id}>
                        {run.status !== "approved" && (
                          <td className="border p-2 text-center">
                            <input
                              type="checkbox"
                              checked={selectedNetIds.includes(n.id)}
                              onChange={() => handleSelect(n.id)}
                            />
                          </td>
                        )}
                        <td className="border p-2">
                          {n.employee.first_name} {n.employee.last_name}
                        </td>
                        <td className="border p-2">{n.gross_pay}</td>
                        <td className="border p-2">{n.total_deductions}</td>
                        <td className="border p-2">{n.net_pay}</td>
                        <td className="border p-2">{n.status}</td>
                        <td className="border p-2">{n.approval_level.name}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Remarks */}
              {run.status !== "approved" && (
                <div className="mt-4">
                <label className="block text-sm font-medium mb-1">
                    Remarks
                </label>
                <InputTextarea
                    value={remarks}
                    onChange={(e) => setRemarks(e.target.value)}
                    placeholder="Enter remarks for approval..."
                    className="w-full text-sm"
                    rows={4}
                    autoResize
                />
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex justify-end gap-4 mt-6">
                {run.status !== "approved" && (
                  <>
                    <button
                      onClick={handleReverse}
                      className="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700"
                    >
                      Reverse
                    </button>
                    <button
                      onClick={handleApprove}
                      className="bg-teal-600 text-white px-4 py-2 rounded hover:bg-teal-700"
                    >
                      Approve Selected
                                      </button>  
                  </>
                )}

                {/* {run.status === "approved" && (
                  <button
                    onClick={handlePay}
                    className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700"
                  >
                    Pay
                  </button>
                )} */}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default ViewCalculatedNetModal;
