export const HUMAN_RESOURCE_ENDPOINTS = {
  DEPARTMENTS: {
    GET_ALL: "/hr/departments",
    GET_BY_ID: (id: string) => `/hr/departments/${id}`,
    ADD: "/hr/departments/create",
    UPDATE: (id: string) => `/hr/departments/${id}/update`,
    DELETE: (id: string) => `/hr/departments/${id}/delete`,
  },
  DESIGNATIONS: {
    GET_ALL: "/hr/designations",
    GET_BY_ID: (id: string) => `/hr/designations/${id}`,
    ADD: "/hr/designations/create",
    UPDATE: (id: string) => `/hr/designations/${id}/update`,
    DELETE: (id: string) => `/hr/designations/${id}/delete`,
  },
  SALARY_STRUCTURES: {
    GET_ALL: "/hr/salarystructures",
    GET_BY_ID: (id: string) => `/hr/salarystructures/${id}`,
    ADD: "/hr/salarystructures",
    UPDATE: (id: string) => `/hr/salarystructures/${id}`,
    DELETE: (id: string) => `/hr/salarystructures/${id}`,
  },
  EMPLOYEES: {
    GET_ALL: "/hr/employees",
    GET_BY_ID: (id: string) => `/hr/employees/${id}`,
    ADD: "/hr/employees/create",
    UPDATE: (id: string) => `/hr/employees/${id}/update`,
    DELETE: (id: string) => `/hr/employees/${id}/delete`,
    ADD_ALLOWANCE: (id: string) => `/hr/employees/${id}/allowances`,
    ADD_DEDUCTION: (id: string) => `/hr/employees/${id}/deductions`,
    UPDATE_ALLOWANCE: (employeeId: string, id: string) => `/hr/employees/${employeeId}/allowances/${id}`,
    UPDATE_DEDUCTION: (employeeId: string, id: string) => `/hr/employees/${employeeId}/deductions/${id}`,
    DELETE_ALLOWANCE: (employeeId: string, id: string) => `/hr/employees/${employeeId}/allowances/${id}`,
    DELETE_DEDUCTION: (employeeId: string, id: string) => `/hr/employees/${employeeId}/deductions/${id}`
  },
  ATTENDENCIES: {
    GET_ALL: "/hr/attendance",
    GET_BY_ID: (id: string) => `/hr/attendance/${id}`,
    ADD: "/hr/attendance/create",
    UPDATE: (id: string) => `/hr/attendance/${id}/update`,
    DELETE: (id: string) => `/hr/attendance/${id}/delete`,
  },
  LEAVE_TYPES: {
    GET_ALL: "/hr/leavetypes",
    GET_BY_ID: (id: string) => `/hr/leavetypes/${id}`,
    ADD: "/hr/leavetypes/create",
    UPDATE: (id: string) => `/hr/leavetypes/${id}/update`,
    DELETE: (id: string) => `/hr/leavetypes/${id}/delete`,
  },
  LEAVE_APPLICATIONS: {
    GET_ALL: "/hr/leaveapplications",
    GET_BY_ID: (id: string) => `/hr/leaveapplications/${id}`,
    ADD: "/hr/leaveapplications/create",
    UPDATE: (id: string) => `/hr/leaveapplications/${id}/update`,
    DELETE: (id: string) => `/hr/leaveapplications/${id}/delete`,
  },
  BONUS_TYPES: {
    GET_ALL: "/hr/bonustypes",
    GET_BY_ID: (id: string) => `/hr/bonustypes/${id}`,
    ADD: "/hr/bonustypes/create",
    UPDATE: (id: string) => `/hr/bonustypes/${id}/update`,
    DELETE: (id: string) => `/hr/bonustypes/${id}/delete`,
  },
  LOAN_TYPES: {
    GET_ALL: "/hr/loantypes",
    GET_BY_ID: (id: string) => `/hr/loantypes/${id}`,
    ADD: "/hr/loantypes",
    UPDATE: (id: string) => `/hr/loantypes/${id}`,
    DELETE: (id: string) => `/hr/loantypes/${id}`,
  },
  DEDUCTION_TYPES: {
    GET_ALL: "/hr/deductiontypes",
    GET_BY_ID: (id: string) => `/hr/deductiontypes/${id}`,
    ADD: "/hr/deductiontypes",
    UPDATE: (id: string) => `/hr/deductiontypes/${id}`,
    DELETE: (id: string) => `/hr/deductiontypes/${id}`,
  },
  ALLOWANCE_TYPES: {
    GET_ALL: "/hr/allowancetypes",
    GET_BY_ID: (id: string) => `/hr/allowancetypes/${id}`,
    ADD: "/hr/allowancetypes",
    UPDATE: (id: string) => `/hr/allowancetypes/${id}`,
    DELETE: (id: string) => `/hr/allowancetypes/${id}`,
  },
  ALLOWANCES: {
    GET_ALL: "/hr/allowances",
    GET_BY_ID: (id: string) => `/hr/allowances/${id}`,
    ADD: "/hr/allowances/create",
    UPDATE: (id: string) => `/hr/allowances/${id}/update`,
    DELETE: (id: string) => `/hr/allowances/${id}/delete`,
  },
  DEDUCTIONS: {
    GET_ALL: "/hr/deductions",
    GET_BY_ID: (id: string) => `/hr/deductions/${id}`,
    ADD: "/hr/deductions/create",
    UPDATE: (id: string) => `/hr/deductions/${id}/update`,
    DELETE: (id: string) => `/hr/deductions/${id}/delete`,
  },
  PAYROLL: {
    GET_ALL: "/hr/payrollrecords",
    GET_BY_ID: (id: string) => `/hr/payroll/${id}`,
    ADD: "/hr/payrollrecords",
    UPDATE: (id: string) => `/hr/payroll/${id}/update`,
    DELETE: (id: string) => `/hr/payroll/${id}/delete`,
  },
  PAYROLL_PERIODS: {
    GET_ALL: "/hr/schedules",
    GET_BY_ID: (id: string) => `/hr/schedules/${id}`,
    ADD: "/hr/schedules",
    GENERATE_GROSS_RUN: (id: string) => `/payroll-runs/${id}/grosses/calculate`,
    GENERATE_NET_PAYROLL: (id: string) => `/payroll-runs/${id}/net/calculate`,
    PAYROLL_PAY: (id: string) => `/payroll-runs/${id}/pay`
  },
  STRUCTURE_ALLOWANCES_AND_DEDUCTIONS: {
    GET_ALL_ALLOWANCES: "/hr/payrollschedules",
    GET_ALLOWANCE_BY_ID: (id: string) => `/hr/payrollschedules/${id}`,
    ADD_ALLOWANCE:(id: string) =>  `/hr/${id}/salary-structures-allowances`,
    UPDATE_ALLOWANCE: (structureId: string, id: string) => `hr/${structureId}/salary-structures-allowances/${id}`,
    DELETE_ALLOWANCE: (id: string) => `/hr/payrollschedules/${id}/delete`,
    GET_ALL_DEDUCTIONS: "/hr/payrollschedules",
    GET_DEDUCTIONS_BY_ID: (id: string) => `/hr/payrollschedules/${id}`,
    ADD_DEDUCTION:(id: string) => `/hr/${id}/salary-structures-deductions`,
    UPDATE_DEDUCTION: (structureId: string, id: string) => `/hr/${structureId}/salary-structures-deductions/${id}`,
    DELETE_DEDUCTION: (id: string) => `/hr/payrollschedules/${id}/delete`,
  },
  EMPLOYEE_LOANS: {
    GET_ALL: "/hr/payrollschedules",
    GET_BY_ID: (id: string) => `/hr/payrollschedules/${id}`,
    ADD: (id: string) => `/hr/employees/${id}/loans`,
    APPROVE: (employeeId: string, id: string) => `hr/employees/${employeeId}/loans/${id}/approve`,
    UPDATE: (id: string) => `/hr/payrollschedules/${id}/update`,
    DELETE: (id: string) => `/hr/payrollschedules/${id}/delete`,
  }
};
