export const MOSS_APP_ENDPOINTS = {
  SLIDERS: {
    GET_ALL: "/sliders",
    GET_BY_ID: (id: string) => `/sliders/${id}`,
    ADD: "/sliders",
    UPDATE: (id: string) => `/sliders/${id}`,
    DELETE: (id: string) => `/sliders/${id}`,
  },
  HEALTH_CONDITIONS: {
    GET_ALL: "/conditions",
    GET_BY_ID: (id: string) => `/conditions/${id}`,
    ADD: "/conditions",
    UPDATE: (id: string) => `/conditions/${id}`,
    DELETE: (id: string) => `/conditions/${id}`,
  },
  INTERESTS: {
    GET_ALL: "/interests",
    GET_BY_ID: (id: string) => `/interests/${id}`,
    ADD: "/interests",
    UPDATE: (id: string) => `/interests/${id}`,
    DELETE: (id: string) => `/interests/${id}`,
  },
  REMINDERS: {
    GET_ALL: "/reminders",
    GET_BY_ID: (id: string) => `/reminders/${id}`,
    ADD: "/reminder",
    UPDATE: (id: string) => `/reminders/${id}`,
    DELETE: (id: string) => `/reminders/${id}`,
  },
  DRUGS: {
    GET_ALL: "/drugs",
    GET_BY_ID: (id: string) => `/drugs/${id}`,
    ADD: "/drugs",
    UPDATE: (id: string) => `/drugs/${id}`,
    DELETE: (id: string) => `/drugs/${id}`,
  },
  FACILITIES: {
    GET_ALL: "/facilities",
    GET_BY_ID: (id: string) => `/facilities/${id}`,
    ADD: "/facilities",
    UPDATE: (id: string) => `/facilities/${id}`,
    DELETE: (id: string) => `/facilities/${id}`,
  },
  TIPS: {
    GET_ALL: "/tips",
    GET_BY_ID: (id: string) => `/tips/${id}`,
    ADD: "/tips",
    UPDATE: (id: string) => `/tips/${id}`,
    DELETE: (id: string) => `/tips/${id}`,
  },
  COMMUNITIES: {
    GET_ALL: "/communities",
    GET_BY_ID: (id: string) => `/communities/${id}`,
    ADD: "/communities",
    UPDATE: (id: string) => `/communities/${id}`,
    DELETE: (id: string) => `/communities/${id}`,
  },
  STORIES: {
    GET_ALL: "/stories",
    GET_BY_ID: (id: string) => `/stories/${id}`,
    ADD: "/stories",
    UPDATE: (id: string) => `/stories/${id}`,
    DELETE: (id: string) => `/stories/${id}`,
  },
  USERS: {
    GET_ALL: "/search_users",
    GET_BY_ID: (id: string) => `/search_users/${id}`,
    ADD: "/search_users",
    UPDATE: (id: string) => `/search_users/${id}`,
    DELETE: (id: string) => `/search_users/${id}`,
  },
  HEALTH_WORKERS: {
    GET_ALL: "/get_health_workers",
    GET_BY_ID: (id: string) => `/get_health_workers/${id}`,
    ADD: "/get_health_workers",
    APPROVE: "/activate_health_worker",
    UPDATE: (id: string) => `/get_health_workers/${id}`,
    DELETE: (id: string) => `/get_health_workers/${id}`,
  },
  APPOINTMENT_TYPES: {
    GET_ALL: "/appointment_types",
    GET_BY_ID: (id: string) => `/appointment_types/${id}`,
    ADD: "/appointment_types",
    UPDATE: (id: string) => `/appointment_types/${id}`,
    DELETE: (id: string) => `/appointment_types/${id}`,
  },
  APPOINTMENTS: {
    GET_ALL: "/appointments",
    GET_BY_ID: (id: string) => `/appointments/${id}`,
    ADD: "/appointments",
    UPDATE: (id: string) => `/appointments/${id}`,
    DELETE: (id: string) => `/appointments/${id}`,
  },
  DASHBOARD: {
    GET_ALL: "/dashboard",
    GET_BY_ID: (id: string) => `/dashboard/${id}`,
    ADD: "/dashboard",
    UPDATE: (id: string) => `/dashboard/${id}`,
    DELETE: (id: string) => `/dashboard/${id}`,
  },
  REMINDER_STATS: {
    GET_ALL: "/remindersstats",
    GET_BY_ID: (id: string) => `/remindersstats/${id}`,
    ADD: "/remindersstats",
    UPDATE: (id: string) => `/remindersstats/${id}`,
    DELETE: (id: string) => `/remindersstats/${id}`,
  },
};
