export const RECRUITMENT_ENDPOINTS = {
    REPORTS: {
        SUMMARY: (startDate?: string, endDate?: string) => `/reports/recruitments/dashboard?from_date=${startDate}&to_date=${endDate}`,
        APPLICATION_SOURCES: (startDate?: string, endDate?: string) => `/reports/recruitments/application-source?from_date=${startDate}&to_date=${endDate}`,
        OFFERS: (startDate?: string, endDate?: string) => `/reports/recruitments/offers?from_date=${startDate}&to_date=${endDate}`,
        INTERVIEW_ACTIVITIES: (startDate?: string, endDate?: string) => `/reports/recruitments/interview-activities?from_date=${startDate}&to_date=${endDate}`,
        APPLICATION_PIPELINES: (startDate?: string, endDate?: string) => `/reports/recruitments/application-pipelines?from_date=${startDate}&to_date=${endDate}`,
    },
    INTERVIEWS: {
        GET_ALL: "/recruitment/interviews",
        GET_BY_ID: (id: string) => `/recruitment/interviews/${id}`,
        ADD: "/recruitment/interviews/create",
        UPDATE: (id: string) => `/recruitment/interviews/${id}/update`,
        DELETE: (id: string) => `/recruitment/interviews/${id}/delete`,
    },
    APPLICANTS: {
        GET_ALL: "/recruitment/applications",
        GET_BY_ID: (id: string) => `/recruitment/applications/${id}`,
        ADD: "/recruitment/applications/create",
        UPDATE: (id: string) => `/recruitment/applications/${id}/update`,
        DELETE: (id: string) => `/recruitment/applications/${id}/delete`,
    },
    OFFER: {
        GET_ALL: "/recruitment/offers",
        GET_BY_ID: (id: string) => `/recruitment/offers/${id}`,
        ADD: "/recruitment/offers/create",
        UPDATE: (id: string) => `/recruitment/offers/${id}/update`,
        DELETE: (id: string) => `/recruitment/offers/${id}/delete`,
    },
    CONTRACT_TERMS: {
        GET_ALL: "/recruitment/contract-terms",
        GET_BY_ID: (id: string) => `/recruitment/contract-terms/${id}`,
        ADD: "/recruitment/contract-terms/create",
        UPDATE: (id: string) => `/recruitment/contract-terms/${id}/update`,
        DELETE: (id: string) => `/recruitment/contract-terms/${id}/delete`,
    },
    COMPANY_COMMUNICATIONS: {
        GET_ALL: "/recruitment/communications",
        GET_BY_ID: (id: string) => `/recruitment/communications/${id}`,
        ADD: "/recruitment/communications/create",
        UPDATE: (id: string) => `/recruitment/communications/${id}/update`,
        DELETE: (id: string) => `/recruitment/communications/${id}/delete`,
        ADD_ATTACHMENT: (id: string) => `/recruitment/communication/attachments/${id}/create`,
    },
    JOB_DISTRIBUTION: {
        GET_ALL: "/recruitment/jobdistributions",
        GET_BY_ID: (id: string) => `/recruitment/jobdistributions/${id}`,
        ADD: "/recruitment/jobdistributions/create",
        UPDATE: (id: string) => `/recruitment/jobdistributions/${id}/update`,
        DELETE: (id: string) => `/recruitment/jobdistributions/${id}/delete`,
    },
    JOB_ORDERS: {
        GET_ALL: "/recruitment/joborders",
        GET_BY_ID: (id: string) => `/recruitment/joborders/${id}`,
        ADD: "/recruitment/joborders/create",
        UPDATE: (id: string) => `/recruitment/joborders/${id}/update`,
        DELETE: (id: string) => `/recruitment/joborders/${id}/delete`,
    },
    JOB_BOARDS: {
        GET_ALL: "/recruitment/jobboards",
        GET_BY_ID: (id: string) => `/recruitment/jobboards/${id}`,
        ADD: "/recruitment/jobboards/create",
        UPDATE: (id: string) => `/recruitment/jobboards/${id}/update`,
        DELETE: (id: string) => `/recruitment/jobboards/${id}/delete`,
    },
    COMMISSION_STRUCTURES: {
        GET_ALL: "/recruitment/commission-structures",
        GET_BY_ID: (id: string) => `/recruitment/commission-structures/${id}`,
        ADD: "/recruitment/commission-structures/create",
        UPDATE: (id: string) => `/recruitment/commission-structures/${id}/update`,
        DELETE: (id: string) => `/recruitment/commission-structures/${id}/delete`,
    },
    COMMUNICATION_TYPES: {
        GET_ALL: "/recruitment/communicationtypes",
        GET_BY_ID: (id: string) => `/recruitment/communicationtypes/${id}`,
        ADD: "/recruitment/communicationtypes/create",
        UPDATE: (id: string) => `/recruitment/communicationtypes/${id}/update`,
        DELETE: (id: string) => `/recruitment/communicationtypes/${id}/delete`,
    },
    COMMUNICATION_TEMPLATES: {
        GET_ALL: "/recruitment/communication-templates",
        GET_BY_ID: (id: string) => `/recruitment/communication-templates/${id}`,
        ADD: "/recruitment/communication-templates/create",
        UPDATE: (id: string) => `/recruitment/communication-templates/${id}/update`,
        DELETE: (id: string) => `/recruitment/communication-templates/${id}/delete`,
    },
    SKILLS: {
        GET_ALL: "/recruitment/skills",
        GET_BY_ID: (id: string) => `/recruitment/skills/${id}`,
        ADD: "/recruitment/skills/create",
        UPDATE: (id: string) => `/recruitment/skills/${id}/update`,
        DELETE: (id: string) => `/recruitment/skills/${id}/delete`,
    },
    CANDIDATE_SEQUENCES: {
        GET_ALL: "/recruitment/candidate-number-sequence",
        UPDATE: (id: string) => `/recruitment/candidate-number-sequences/${id}/update`,
    },
    INVOICE_SEQUENCES: {
        GET_ALL: "/recruitment/invoice-number-sequences",
        UPDATE: (id: string) => `/recruitment/invoice-number-sequences/${id}/update`,
    },
    CANDIDATES: {
        GET_ALL: "/recruitment/candidates",
        GET_BY_ID: (id: string) => `/recruitment/candidates/${id}`,
        ADD: "/recruitment/candidates/create",
        UPDATE: (id: string) => `/recruitment/candidates/${id}/update`,
        DELETE: (id: string) => `/recruitment/candidates/${id}/delete`,
    },
    COMPANY: {
        GET_ALL: "/recruitment/companies",
        GET_BY_ID: (id: string) => `/recruitment/companies/${id}`,
        ADD: "/recruitment/companies/create",
        UPDATE: (id: string) => `/recruitment/companies/${id}/update`,
        DELETE: (id: string) => `/recruitment/companies/${id}/delete`,
    }
};