export const SALES_ENDPOINTS = {
  QUOTES: {
    GET_ALL: "/sales/quotations",
    GET_BY_ID: (id: string) => `/sales/quotations/${id}`,
    ADD: "/sales/quotations/create",
    UPDATE: (id: string) => `/erp/sales/quotations/${id}/update`,
    DELETE: (id: string) => `/erp/sales/quotations/${id}/delete`,
  },
  LEADS: {
    GET_ALL: "/sales/leads",
    GET_BY_ID: (id: string) => `/sales/leads/${id}`,
    ADD: "/sales/leads/create",
    UPDATE: (id: string) => `/sales/leads/${id}/update`,
    DELETE: (id: string) => `/sales/leads/${id}/delete`,
  },
  CUSTOMER_ORDERS: {
    GET_ALL: "/sales/customer_orders",
    GET_BY_ID: (id: string) => `/sales/customer_orders/${id}`,
    ADD: "/sales/customer_orders/create",
    UPDATE: (id: string) => `/sales/customer_orders/${id}/update`,
    DELETE: (id: string) => `/sales/customer_orders/${id}/delete`,
  },
  DISTRIBUTION_ORDERS: {
    GET_ALL: "/sales/distribution_orders",
    GET_BY_ID: (id: string) => `/sales/distribution_orders/${id}`,
    ADD: "/sales/distribution_orders/create",
    UPDATE: (id: string) => `/sales/distribution_orders/${id}/update`,
    DELETE: (id: string) => `/sales/distribution_orders/${id}/delete`,
  },
  BRANDS: {
    GET_ALL: "/sales/brands",
    GET_BY_ID: (id: string) => `/sales/brands/${id}`,
    ADD: "/sales/brands/create",
    UPDATE: (id: string) => `/sales/brands/${id}/update`,
    DELETE: (id: string) => `/sales/brands/${id}/delete`,
  },
  CURRENCIES: {
    GET_ALL: "/currencies",
    GET_BY_ID: (id: string) => `/currencies/${id}`,
    ADD: "/currencies/add",
    UPDATE: (id: string) => `/currencies/${id}`,
    DELETE: (id: string) => `/currencies/${id}`,
  },
  ITEM_CATEGORIES: {
    GET_ALL: "/sales/item_categories",
    ADD: "/sales/item_categories/create",
    UPDATE: (id: string) => `/sales/item_categories/${id}/update`,
    DELETE: (id: string) => `/sales/item_categories/${id}/delete`,
  },
  ITEMS: {
    GET_ALL: "/sales/items",
    ADD: "/sales/items/create",
    UPDATE: (id: string) => `/sales/items/${id}/update`,
    DELETE: (id: string) => `/sales/items/${id}/delete`,
  },

  SUPPLIERS: {
    GET_ALL: "/people/suppliers",
    GET_BY_ID: (id: string) => `/people/suppliers/${id}`,
    ADD: "/people/suppliers/create",
    UPDATE: (id: string) => `/people/suppliers/${id}/update`,
    DELETE: (id: string) => `/people/suppliers/${id}`,
  },

  CUSTOMERS: {
    GET_ALL: "/people/customers",
    GET_BY_ID: (id: string) => `/people/customers/${id}`,
    ADD: "/people/customers/create",
    UPDATE: (id: string) => `/people/customers/${id}/update`,
    DELETE: (id: string) => `/people/customers/${id}`,
  },
  TRUCKS: {
    GET_ALL: "/people/trucks",
    GET_BY_ID: (id: string) => `/people/trucks/${id}`,
    ADD: "/people/trucks/create",
    UPDATE: (id: string) => `/people/trucks/${id}/update`,
    DELETE: (id: string) => `/people/trucks/${id}`,
  },
  DRIVERS: {
    GET_ALL: "/people/drivers",
    GET_BY_ID: (id: string) => `/people/drivers/${id}`,
    ADD: "/people/drivers/create",
    UPDATE: (id: string) => `/people/drivers/${id}/update`,
    DELETE: (id: string) => `/people/drivers/${id}`,
  },
};
